### ISSUE TITLE
エラーハンドリング

### ISSUE THREAD

**Issue by nalabjp** [nalabjp/imadoko#1]
APIがエラーを返した場合にそのまま死んでる。

```
2015-06-22T15:17:06.560Z [INFO]: PUT trello card:
2015-06-22T15:17:07.489Z [INFO]: PUT trello card: card was moved to "away"
2015-06-22T17:05:30.986Z [INFO]: PUT trello card:
/Users/kimura/dev/imadoko/lib/trello.js:147
      if (err) throw err;
                     ^
Error: getaddrinfo ENOTFOUND api.trello.com
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)

```

**Comment by nalabjp** [comment]
https://github.com/nalabjp/imadoko/commit/a1e4e18e93ff335050d33ec739cceb3fd014f4b5

api分だけとりあえず。
